### PR TITLE
Fix foodcritic messages

### PR DESCRIPTION
**Pull request by damphyr**

### CODE REVIEW

**Comment by tknerr** [comment]
:+1: 

Why do you need to sandbox, though?

**Comment by damphyr** [comment]
I just copied an example I found online. Didn't really get in too deep :smile:

**Comment by damphyr** [comment]
Also it's behaving weirdly: I get different messages locally than I do from TravisCI and the ones I get locally are false positives. I have different Ruby versions setup but if foodcritic is dependent on the Ruby version then it's not really reliable as a linting tool for recipe.

**Comment by tknerr** [comment]
weird... never had that issue, but sounds like it would be woth a look on friday

**Pull request merged**
